### PR TITLE
fix broken img

### PR DESCRIPTION
**Pull request by ansonla3**

### CODE REVIEW

**Comment by laboon** [comment]
This also moves the "directional" next/previous arrows to their own grey box, moving them out of the black box at the bottom.  Is this intentional?

Before:

image


After:

image

**Comment by ansonla3** [comment]
> This also moves the "directional" next/previous arrows to their own grey box, moving them out of the black box at the bottom. Is this intentional?
> 
> Before:
> 
> image
> 
> After:
> 
> image

**Comment by ansonla3** [comment]
@laboon the new design was made by Iggy   :)

**Comment by laboon** [comment]
👍

**Comment by laboon** [comment]
I had an old version of master.  Sorry about that.  Approved.

**Review by laboon — APPROVED** [review]
👍

**Pull request merged**
