### PR TITLE
docs: Fix typos in w3f polkadot wiki

### PR DESCRIPTION
**Pull request by ltfschoen**
This PR just proposes miscellaneous things that I think need to change

### CODE REVIEW

**Comment by lsaether** [comment]
@ltfschoen The CI caught some spelling "errors", could you see if they are right and if so you can add them to the `.spelling` ignore file.

**Comment by ltfschoen** [comment]
> @ltfschoen The CI caught some spelling "errors", could you see if they are right and if so you can add them to the `.spelling` ignore file.

i've pushed commits updating .spelling and rebasing with latest master

**Review by laboon — APPROVED** [review]
This all looks good to me.

**Review by lsaether — APPROVED** [review]
LGTM

**Pull request merged**
